---
title: "R Markdown"
author: "Vlad"
date: "2023-03-24"
output: html_document
---

# Vlad's Example   
## Setting up my environment
Notes: setting up my R environment by loading the 'tidyverse' and 'palmerpenguins' packages

```{r}
library(tidyverse)
library(palmerpenguins)
```

### SCATERPLOTS
```{r}
ggplot(data = penguins)+ 
  geom_smooth(mapping = aes(x = flipper_length_mm, y = body_mass_g), color="blue")+
  geom_point(mapping = aes(x = flipper_length_mm, y = body_mass_g,shape = species, alpha = species), color="purple")
ggplot(data = penguins)+ 
  geom_smooth(mapping = aes(x = flipper_length_mm, y = body_mass_g, linetype = species))
ggplot(data = penguins)+ 
  geom_jitter(mapping = aes(x = flipper_length_mm, y = body_mass_g))
```

# BARCHARTS
```{r}
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut, fill=clarity))+
  facet_grid(~cut)
```

# FACET
```{r}
ggplot(data = penguins)+ 
  geom_smooth(mapping = aes(x = flipper_length_mm, y = body_mass_g, color=species))+
  facet_wrap(~species)
```

# LABELS
```{r}
ggplot(data = penguins)+ 
  geom_smooth(mapping = aes(x = flipper_length_mm, y = body_mass_g, color=species))+
  labs(title="PALMER Penguins: Body Mass vs. Flipper Length")
```

# ANNOTATIONS
```{r}
ggplot(data = penguins)+ 
  geom_smooth(mapping = aes(x = flipper_length_mm, y = body_mass_g, color=species))+
  annotate("text", x=220, y=3500, label="The Gentoos are the largest")
```
